### ISSUE TITLE
Readout to numpy array

### ISSUE THREAD

**Issue by schote** [schote/spectrum-console#21]
When an ADC gate event finished, the acquired data from that gate is transferred from card to PC.
The variable, which contains the transferred data samples is of type list at the moment.
Performance-wise it would be better to have the received data as numpy arrays directly.

e.g. in rx_device.py: line 321 `gate_data = rx_data[index_0 : index_0 + int(total_bytes / 2)]`, the variable `gate_data` should be a numpy array

- [x] Get gate data as numpy array, without casting between list/ndarray, the readout-arrays can still be appended to a list
- [x] Measure timing of gata data extraction (using list and ndarray), what is the improvement?
- [ ] Use lineprofiler to analyse further improvements during readout
```
from line_profiler import profile

@profile
def func(x):
    ...
```

**Comment by berksilemek** [comment]
# Performance analysis working with numpy array instead of list
Rx buffer is provided as list. If we would like to continue with numpy arrays:
For example instead of using 
gate_data = rx_data[index_0 : index_0 + int(total_bytes / 2)]  //Approximately 2 ms
using this:
gate_data = ctonp.as_array(rx_data[index_0 : index_0 + int(total_bytes / 2)]) // Approximately 8 ms

At the moment there is not buffer overflow issues. E.g., with TSE sequence. More tests can be done by introducing some other stressful sequence. Further tests are not needed for now.                       

What do you consider?
