### ISSUE TITLE
BUG: Number of raw readout samples varies between gates

### ISSUE THREAD

**Issue by schote** [schote/spectrum-console#31]
- Number of samples regularly varies between +-1 (most probably due to some rounding issues)
- At some irregular events, the number of readout samples varies by more than 2000/3000
- Number of left-over bytes is accumulating in sequences with many readout events (problem only becomes visible here)
- First readout is always as expected (no problem with single readout protocols)

This bug is related to #21 and should be fixed with that issue. 
Performance analysis might also help to identify any memory read or access delays.

**Comment by berksilemek** [comment]
# Performance analysis working with numpy array instead of list
Rx buffer is provided as list. If we would like to continue with numpy arrays:
For example instead of using 
gate_data = rx_data[index_0 : index_0 + int(total_bytes / 2)]  //Approximately 2 ms
using this:
gate_data = ctonp.as_array(rx_data[index_0 : index_0 + int(total_bytes / 2)]) // Approximately 8 ms

At the moment there is not buffer overflow issues. E.g., with TSE sequence. More tests can be done by introducing some other stressful sequence. Further tests are not needed for now.
